version: '3'
services:
  nginx:
    image: 'nginx:1.23'
    container_name: nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./web:/var/www/web
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - web
  web:
    build: ./php
    container_name: web
    volumes:
      - ./web:/var/www/web
    links:
      - mysql
  mysql:
    image: 'mysql:5.7'
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp=true
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=reiel
